### ISSUE TITLE
How to pip install tsensor

### ISSUE THREAD

**Issue by DeqianBai** [mertensu/transformer-tutorial#1]
there was an error :
3 import matplotlib.pyplot as plt
      4 import torch
----> 5 import tsensor
      6 from ipywidgets import interact, interactive, fixed, interact_manual
      7 import ipywidgets as widgets

ModuleNotFoundError: No module named 'tsensor'

but can not install tsensor via pip 

Win10  Anconda3 python 3.6

**Comment by mertensu** [comment]
You might wanna take a look at the tensor-sensor github repo: https://github.com/parrt/tensor-sensor

**Comment by anuragg1209** [comment]
I have installed tensor-sensor successfully but still not able to import tsensor module. 

It throws the error ModuleNotFoundError: No module named 'tsensor'. Any idea why this error is coming?
